Import users by CSV file + Upload file management
YunoHost/yunohost-admin pull request #357
Opened 2021-05-08 20:54 UTC by zamentur

### The problem
Several yunohost admins need a way to import several users. That's completely in the use case of small or medium communities servers (CHATONS & co).

### The solution
I have decided to develop the new view inside the vuejs admin to avoid to do the work twice.

![import users](https://user-images.githubusercontent.com/4080016/100594978-a10b0980-32fa-11eb-925f-2a01dcb9a43e.png)

If users check the deleted checkbox a popover will be triggered to ask confirmation.

### Status
Ready for first review

### How to test
You need the PR about file args on moulinette and yunohost repo.

### Other info
This PR was entirely financed by the new CNAM fablab. Thanks to them :) .

2021-05-08 20:57 UTC, zamentur commented
See if this commit is better than current system : https://github.com/YunoHost/yunohost-admin/pull/328/commits/7da0056e913633e6daaf3d0146708836097fc182

Don't know what to do for this unrelated commit from the other PR https://github.com/YunoHost/yunohost-admin/pull/328/commits/2da3419715765deefb6fcc1b54b54cfd469df38b

2021-08-08 21:32 UTC, ericgaspar requested changes

2021-08-08 21:32 UTC, ericgaspar commented on app/src/i18n/locales/en.json
>          "githubLink": "Url must be a valid Github link to a repository",
```suggestion
        "githubLink": "URL must be a valid GitHub link to a repository",
```

2021-08-08 21:32 UTC, ericgaspar commented on app/src/i18n/locales/en.json
> +    "users_import_update_desc": "If checked, all existing users contained in the csv file will be updated with the ne new value",
```suggestion
    "users_import_update_desc": "If checked, all existing users contained in the CSV file will be updated with the ne new value",
```

2021-08-08 21:32 UTC, ericgaspar commented on app/src/i18n/locales/en.json
> +    "users_import_delete_desc": "If checked, all existing users that are not in the csv file will be deleted (and purged).",
```suggestion
    "users_import_delete_desc": "If checked, all existing users that are not in the CSV file will be deleted (and purged).",
```

2021-09-03 14:55 UTC, alexAubin commented on app/src/i18n/locales/en.json
> +    "users_import_csv_file_desc": "The CSV file should be in UTF-8 and with columns username, password, groups, email and quota. See <a href=''>example import csv file</a>.",
Bumpity bump @zamentur in case you know what you intended to do with this href/link...

2021-09-06 16:08 UTC, zamentur commented on app/src/i18n/locales/en.json
> +    "users_import_csv_file_desc": "The CSV file should be in UTF-8 and with columns username, password, groups, email and quota. See <a href=''>example import csv file</a>.",
```suggestion
    "users_import_csv_file_desc": "The CSV file should be in UTF-8 and with columns username, password, groups, email and quota. For an example import CSV file, you can <a href='/yunohost/api/users/export' target='_BLANK'>export your users in CSV file</a> and change the file.",
```

2021-09-06 16:18 UTC, alexAubin approved these changes
:tada:

2021-09-06 17:32 UTC, merged